apiVersion: v1
kind: Service
metadata:
  name: movie-app-api-gateway
spec:
  type: LoadBalancer
  clusterIP: 10.96.0.13
  loadBalancerIP: 34.83.1.21
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    name: movie-app-api-gateway