# google-cloud-deploy

server:
  port: 8080
  error:
    include-message: always

spring:
  config:
    activate:
      on-profile: "google-cloud-deploy"
  application:
    name: eureka-server-2
  data:
    redis:
      host: 10.96.0.15
      port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.96.0.11:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    statusPageUrlPath: http://34.83.1.21/api/v1/admin/${MY_POD_IP}/swagger-ui.html
    preferIpAddress: true

springdoc:
  api-docs:
    path: /api/v1/admin/${MY_POD_IP}/v3/api-docs
  show-actuator: true
  swagger-ui:
    path: /api/v1/admin/${MY_POD_IP}/swagger-ui.html
    disable-swagger-default-url: true

management:
  api-docs:
    path: /api/v1/admin/${MY_POD_IP}/v3/api-docs
  endpoints:
    enabled-by-default: true
    web:
      base-path: /api/v1/admin/${MY_POD_IP}/actuator
      exposure:
        include: "*"

logging:
  file:
    name: ./logs/eureka-server-2.log
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

---
# docker
