# google-cloud-deploy

server:
  port: 8080
  error:
    include-message: always

spring:
  config:
    activate:
      on-profile: "google-cloud-deploy"
  application:
    name: push-notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: projectmovieapp@gmail.com
    password: dcxosgeqobeupkbb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: 10.96.0.14
    port: 5672
    username: admin
    password: admin
  data:
    redis:
      host: 10.96.0.15
      port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.96.0.11:8761/eureka, http://10.96.0.12:8761/eureka
    fetchRegistry: true
    registerWithEureka: true
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    statusPageUrlPath: http://34.83.1.21/api/v1/admin/${MY_POD_IP}/swagger-ui.html
    preferIpAddress: true

springdoc:
  api-docs:
    path: /api/v1/admin/${MY_POD_IP}/v3/api-docs
  show-actuator: true
  swagger-ui:
    path: /api/v1/admin/${MY_POD_IP}/swagger-ui.html
    disable-swagger-default-url: true

management:
  api-docs:
    path: /api/v1/admin/${MY_POD_IP}/v3/api-docs
  endpoints:
    enabled-by-default: true
    web:
      base-path: /api/v1/admin/${MY_POD_IP}/actuator
      exposure:
        include: "*"

logging:
  file:
    name: ./logs/push-notification.log

---
# docker

server:
  port: 8080
  error:
    include-message: always

spring:
  config:
    activate:
      on-profile: "docker"
  application:
    name: push-notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: projectmovieapp@gmail.com
    password: dcxosgeqobeupkbb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
  data:
    redis:
      host: redis
      port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
    fetchRegistry: true
    registerWithEureka: true
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    statusPageUrlPath: http://localhost/api/v1/admin/push-notification/actuator

springdoc:
  show-actuator: true
  use-management-port: true
  swagger-ui:
    path: /swagger-ui.html

management:
  server:
    port: 8090
  endpoints:
    enabled-by-default: true
    web:
      base-path: /api/v1/admin/push-notification/actuator
      exposure:
        include: "*"
  #      cors: # according to docs this is disabled by default unless values specified
  #        allowed-origins: "http://localhost:4200"
  #        allowed-methods: GET,POST
  security:
    enabled: false
    sessions: never

logging:
  file:
    name: ./logs/push-notification.log