apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-app-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      name: movie-app-rabbitmq
  template:
    metadata:
      name: movie-app-rabbitmq-pod
      labels:
        name: movie-app-rabbitmq
    spec:
      containers:
        - name: movie-app-rabbitmq-service
          image: us-west1-docker.pkg.dev/aerial-venture-386206/movie-app-rabbitmq/movie-app-rabbitmq:latest
#          imagePullPolicy: Never   # So it doesn't pull the image from remote registry
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
