apiVersion: v1
kind: Service
metadata:
  name: movie-app-rabbitmq-ext
spec:
  type: LoadBalancer
  loadBalancerIP: 34.83.1.21
  ports:
    - port: 15672
      protocol: TCP
      targetPort: 15672
  selector:
    name: movie-app-rabbitmq