apiVersion: v1
kind: Service
metadata:
  name: movie-app-rabbitmq
spec:
  type: ClusterIP
  clusterIP: 10.96.0.14
  ports:
    - port: 5672
      protocol: TCP
      targetPort: 5672
      name: message-port
    - port: 15672
      protocol: TCP
      targetPort: 15672
      name: ui-port
  selector:
    name: movie-app-rabbitmq
