apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-app-user-movie
spec:
  replicas: 1
  selector:
    matchLabels:
      name: movie-app-user-movie
  template:
    metadata:
      name: movie-app-user-movie-pod
      labels:
        name: movie-app-user-movie
    spec:
      containers:
        - name: movie-app-user-movie-service
          image: us-west1-docker.pkg.dev/aerial-venture-386206/movie-app-user-movie/movie-app-user-movie:latest
#          imagePullPolicy: Never   # So it doesn't pull the image from remote registry
          ports:
            - containerPort: 8080
            - containerPort: 8090
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SPRING_PROFILES_ACTIVE
              value: "google-cloud-deploy"
