apiVersion: v1
kind: Service
metadata:
  name: movie-app-redis
spec:
  type: LoadBalancer
  clusterIP: 10.96.0.15
  loadBalancerIP: 34.83.1.21
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    name: movie-app-redis
