FROM bellsoft/liberica-openjdk-alpine:17
WORKDIR usr/src
ADD ./target/eureka-server-2-0.0.1-SNAPSHOT.jar /usr/src/eureka-server-2-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","eureka-server-2-0.0.1-SNAPSHOT.jar"]